/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  introduction: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['intro', 'v3-overview'],
    },
  ],
  smartcontracts: [
    {
      type: 'category',
      label: 'Smart Contracts',
      items: ['smart-contracts/zora-V3', 'smart-contracts/zora-auction-house'],
    },
  ],
  api: [
    {
      type: 'category',
      label: 'Zora API',
      items: [
        'zora-api/zora-api-intro', 
        'zora-api/zora-api-sample-queries',
        'zora-api/zdk-api',
        {
          type: 'category',
          label: 'Guides',
          collapsed: false,
          items: ['zora-api/api-punks-market'],
        },
      ],
    },
  ],
  devtools: [
    {
      type: 'category',
      label: 'Dev Tools',
      items: [],
    },
  ],
}
